### ISSUE TITLE
Openload returns error when remote uploading from S3

### ISSUE THREAD

**Issue by brunohenriquesk1** [saschazar21/node-openload#1] opened 2017-07-04 05:13 UTC
Im trying to upload a content from my amazon s3 and it always returns Status: error,
 my code on the server-side
 

```
>   let obj = {
            url:'https://s3-us-west-1.amazonaws.com/mybucket/img.jpg',
            headers:{
                User-Agent:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like 
                  Gecko) Chrome/59.0.3071.115 Safari/537.36'
                }
        }
  
        ol.remoteUpload(obj)
```

any ideia? thanks

**Comment by saschazar21** [comment] 2017-07-04 11:28
Hi @98falcon, 
I tried to reproduce your error and can confirm there is a bug when uploading arbitrary files hosted on S3.
Sadly, this bug is caused by Openload and not by *node-openload*.
My suggestion therefore is to file a bug using Openload's [contact form](https://openload.co/contact).

If you are interested, the code block below is the test I tried to reproduce the bug. Every task is resulting in a successful outcome, but if you look at the result of the *remoteUploadStatus* endpoint, it will tell you that only the last upload task (*image upload*) succeeded, while the other ones failed.  
Please install [mocha](mocha) and [node-openload](https://www.npmjs.com/package/node-openload) as dependencies before running this script via `mocha script-name.js`.  
(Hint: `npm install -g mocha` to run it straight from the command line).

The only **workaround** for this issue I can suggest you, is to first download your file as a buffer before uploading it to Openload (similar to line [130](https://github.com/saschazar21/node-openload/blob/master/test/test.js#L130) in `test/test.js`).

If this answers your question, I will close this issue in the next days, if it doesn't please comment below.

Thanks and good luck!

```JavaScript
const openload = require('node-openload');

const ol = openload({
  api_login: ' ',     // your API login here
  api_key: ' ',       // your API key here
});

describe('Remote upload', function remoteDownload() {
  it('should upload a PDF from Amazon AWS to Openload', () => ol.remoteUpload({
    url: 'https://s3-us-west-1.amazonaws.com/papaya-download/sdk/Documentation/AppFlood+iOS+v1.6+Integration+Guide+June-20140429.pdf',
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
    },
  })
  .then(res => console.log(res)));

  it('should upload a DOCX from Amazon AWS to Openload', () => ol.remoteUpload({
    url: 'https://s3-us-west-1.amazonaws.com/para-temp/Extool+Platform+for+R+developer.docx',
  })
  .then(res => console.log(res)));

  it('should upload an arbitrary image from the internet to Openload', () => ol.remoteUpload({
    url: 'http://newhampshirehypnosis.com/wp-content/uploads/2013/05/stress.png',
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
    },
  })
  .then(res => console.log(res)));

  it('should fetch information about previous remote uploads', () => ol.remoteUploadStatus()
  .then(res => console.log(res)));
});
```

**Closed as completed** 2017-07-08 13:23 UTC
